{{- if .Values.customPostgresql.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: postgresql-rw-nodeport
  namespace: {{ .Values.customPostgresql.namespace }}
spec:
  type: NodePort
  selector:
    cnpg.io/cluster: postgresql
    role: primary
  ports:
  - port: 5432
    targetPort: 5432
    protocol: TCP
    name: postgresql
    nodePort: {{ .Values.customPostgresql.nodePort }}
{{- end }}
