{{- if .Values.customPgadmin.enabled }}
apiVersion: v1
kind: Secret
metadata:
  name: pgadmin-secret
  namespace: {{ .Values.customPgadmin.namespace }}
type: Opaque
stringData:
  PGADMIN_DEFAULT_EMAIL: {{ .Values.customPgadmin.adminEmail }}
  PGADMIN_DEFAULT_PASSWORD: {{ .Values.customPgadmin.adminPassword }}
  PGADMIN_DB_PASSWORD: {{ .Values.customPgadmin.dbPassword }}
{{- end }}
