apiVersion: org.eclipse.che/v2
kind: CheCluster
metadata:
  name: eclipse-che
  namespace: eclipse-che
spec:
  networking:
    domain: {{ .Values.domain | quote }}
    tlsSecretName: {{ .Values.tlsSecretName | quote }}
    ingressClassName: {{ .Values.ingressClassName | quote }}
    annotations:
      traefik.ingress.kubernetes.io/router.entrypoints: web,websecure
    auth:
      oAuthClientName: {{ .Values.auth.oAuthClientName | quote }}
      oAuthSecret: {{ .Values.auth.oAuthSecret | quote }}
      identityProviderURL: {{ .Values.auth.identityProviderURL | quote }}
  components:
    cheServer:
      extraProperties:
        CHE_KEYCLOAK_SKIP__SERVER_CERTIFICATE__VALIDATION: "true"
        CHE_KEYCLOAK_AUTH__INTERNAL__SERVER__URL: "http://keycloak-http.keycloak.svc.cluster.local/auth"
  devEnvironments:
    storage:
      pvcStrategy: per-workspace
