---
# keycloak-credentials in keycloak namespace
apiVersion: external-secrets.io/v1beta1
kind: ClusterExternalSecret
metadata:
  name: keycloak-credentials
spec:
  namespaceSelectors:
    - matchExpressions:
        - key: kubernetes.io/metadata.name
          operator: In
          values:
            - keycloak
  refreshTime: "1h"
  externalSecretSpec:
    secretStoreRef:
      name: vault-backend
      kind: ClusterSecretStore
    target:
      name: keycloak-credentials
    data:
      - secretKey: db_password
        remoteRef:
          key: {{ .Values.global.env }}/keycloak
          property: db_password
---
# postgresql-admin in keycloak namespace (used by db-init-job)
apiVersion: external-secrets.io/v1beta1
kind: ClusterExternalSecret
metadata:
  name: keycloak-postgresql-admin
spec:
  namespaceSelectors:
    - matchExpressions:
        - key: kubernetes.io/metadata.name
          operator: In
          values:
            - keycloak
  refreshTime: "1h"
  externalSecretSpec:
    secretStoreRef:
      name: vault-backend
      kind: ClusterSecretStore
    target:
      name: postgresql-admin
    data:
      - secretKey: admin_password
        remoteRef:
          key: {{ .Values.global.env }}/postgresql
          property: admin_password
---
# freeipa-credentials in keycloak namespace (used by keycloak-operator)
apiVersion: external-secrets.io/v1beta1
kind: ClusterExternalSecret
metadata:
  name: freeipa-credentials
spec:
  namespaceSelectors:
    - matchExpressions:
        - key: kubernetes.io/metadata.name
          operator: In
          values:
            - keycloak
  refreshTime: "1h"
  externalSecretSpec:
    secretStoreRef:
      name: vault-backend
      kind: ClusterSecretStore
    target:
      name: freeipa-credentials
    data:
      - secretKey: admin_password
        remoteRef:
          key: {{ .Values.global.env }}/freeipa
          property: admin_password
      - secretKey: ldap_service_user_password
        remoteRef:
          key: {{ .Values.global.env }}/freeipa
          property: ldap_service_user_password
