---
# plane-credentials in plane namespace
apiVersion: external-secrets.io/v1beta1
kind: ClusterExternalSecret
metadata:
  name: plane-credentials
spec:
  namespaceSelectors:
    - matchExpressions:
        - key: kubernetes.io/metadata.name
          operator: In
          values:
            - plane
  refreshTime: "1h"
  externalSecretSpec:
    secretStoreRef:
      name: vault-backend
      kind: ClusterSecretStore
    target:
      name: plane-credentials
    data:
      - secretKey: secret_key
        remoteRef:
          key: {{ .Values.global.env }}/plane
          property: secret_key
      - secretKey: live_server_secret_key
        remoteRef:
          key: {{ .Values.global.env }}/plane
          property: live_server_secret_key
      - secretKey: rabbitmq_password
        remoteRef:
          key: {{ .Values.global.env }}/plane
          property: rabbitmq_password
      - secretKey: pg_password
        remoteRef:
          key: {{ .Values.global.env }}/plane
          property: pg_password
      - secretKey: minio_password
        remoteRef:
          key: {{ .Values.global.env }}/plane
          property: minio_password
