apiVersion: external-secrets.io/v1beta1
kind: ClusterSecretStore
metadata:
  name: vault-backend
spec:
  provider:
    vault:
      server: {{ .Values.vault.url | quote }}
      path: "secret"
      version: "v2"
      auth:
        kubernetes:
          mountPath: {{ .Values.vault.kubeAuthPath | quote }}
          role: {{ .Values.vault.role | quote }}
          serviceAccountRef:
            name: "external-secrets"
            namespace: "external-secrets"
