---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: wait-for-eso-webhook
  namespace: {{ .Release.Namespace }}
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: wait-for-eso-webhook
rules:
  - apiGroups: [""]
    resources: ["endpoints"]
    verbs: ["get", "list"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: wait-for-eso-webhook
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: wait-for-eso-webhook
subjects:
  - kind: ServiceAccount
    name: wait-for-eso-webhook
    namespace: {{ .Release.Namespace }}
