apiVersion: v1
kind: Service
metadata:
  name: {{ include "certa.fullname" . }}-postgresql
  namespace: {{ include "certa.namespace" . }}
  labels:
    {{- include "certa.labels" . | nindent 4 }}
    app.kubernetes.io/component: postgresql
spec:
  type: {{ .Values.postgresql.service.type }}
  ports:
  - port: {{ .Values.postgresql.service.port }}
    targetPort: {{ .Values.postgresql.service.port }}
    protocol: TCP
    name: postgresql
  selector:
    {{- include "certa.selectorLabels" . | nindent 4 }}
    app.kubernetes.io/component: postgresql
