apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: code-server
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    repoURL: https://swipentap.github.io/charts
    chart: code-server
    targetRevision: "1.0.0-129"
    helm:
      releaseName: code-server
      values: |
        continue:
          enabled: true
          ollamaApiBase: "http://ollama.ollama.svc.cluster.local:11434"
          model: llama3.2:3b
          tabAutocompleteModel: llama3.2:3b
          embeddingsModel: nomic-embed-text
        continueInstallExtension: true
        ingress:
          enabled: true
          ingressClassName: traefik
          annotations:
            traefik.ingress.kubernetes.io/router.entrypoints: web,websecure
          hosts:
            - host: code-server.{{ .Values.global.domain }}
              paths:
                - /
          tls:
            - hosts:
                - code-server.{{ .Values.global.domain }}
              secretName: {{ .Values.global.tlsSecret }}
        persistence:
          storageClass: local-path
  destination:
    server: https://kubernetes.default.svc
    namespace: code-server
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
    - CreateNamespace=true
