apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: devworkspace-operator
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    repoURL: https://github.com/devfile/devworkspace-operator
    targetRevision: {{ .Values.devworkspaceOperatorRevision | quote }}
    path: deploy/deployment/kubernetes/objects
  destination:
    server: https://kubernetes.default.svc
    namespace: devworkspace-controller
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
    - CreateNamespace=true
    - ServerSideApply=true
