apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: eclipse-che-operator
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    repoURL: {{ .Values.chartsRepo }}
    chart: eclipse-che-operator
    targetRevision: {{ .Values.eclipseCheOperatorChartRevision | quote }}
    helm:
      releaseName: eclipse-che-operator
      values: {}
  destination:
    server: https://kubernetes.default.svc
    namespace: eclipse-che
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
    - CreateNamespace=true
    - ServerSideApply=true
