apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: harbor-rbac
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    repoURL: {{ .Values.chartsRepo | quote }}
    chart: harbor-rbac
    targetRevision: {{ .Values.harborRbacChartRevision | quote }}
  destination:
    server: https://kubernetes.default.svc
    namespace: harbor
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
    - CreateNamespace=true
