apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: keycloak
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    repoURL: {{ .Values.chartsRepo | quote }}
    chart: keycloak-operator
    targetRevision: {{ .Values.keycloakOperatorChartRevision | quote }}
    helm:
      releaseName: keycloak
      valuesObject:
        extraInitContainers:
          - name: wait-for-postgresql
            image: busybox:1.36
            command:
              - sh
              - -c
              - |
                until nslookup postgresql-rw.postgresql.svc.cluster.local; do
                  echo "waiting for postgresql..."
                  sleep 2
                done
        hostname: "auth.{{ .Values.global.domain }}"
        tlsSecret: {{ .Values.global.tlsSecret }}
        ldapBaseDn: "dc={{ join ",dc=" (splitList "." .Values.freeipa.domain) }}"
        sonarqubeUrl: "https://sonar.{{ .Values.global.domain }}"
        freeipaHostname: {{ .Values.freeipa.hostname | quote }}
        existingFreeipaSecret: freeipa-credentials
        gitea:
          enabled: true
          url: "https://gitea.{{ .Values.global.domain }}"
          existingOauthSecret: "gitea-oauth-secret"
          oauthSecretKey: "oauth_client_secret"
  destination:
    server: https://kubernetes.default.svc
    namespace: keycloak
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
    - CreateNamespace=true
    - Replace=true
