apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: operatorhub-catalog
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "-1"
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    repoURL: {{ .Values.chartsRepo | quote }}
    chart: operatorhub-catalog
    targetRevision: {{ .Values.operatorhubCatalogChartRevision | quote }}
  destination:
    server: https://kubernetes.default.svc
    namespace: olm
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
  syncOptions:
  - CreateNamespace=true
