apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: rabbitmq
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    repoURL: https://groundhog2k.github.io/helm-charts/
    chart: rabbitmq
    targetRevision: {{ .Values.rabbitmqChartRevision | quote }}
    helm:
      releaseName: rabbitmq
      valuesObject:
        settings:
          user: admin
          password: admin
          erlangCookie: secreterlangcookiefortherabbitmqcluster
        storage:
          className: local-path
          requestedSize: 2Gi
        managementPlugin:
          enabled: true
        ingress:
          enabled: true
          className: traefik
          annotations:
            traefik.ingress.kubernetes.io/router.entrypoints: web,websecure
          hosts:
            - host: rabbitmq.{{ .Values.global.domain }}
              paths:
                - path: /
                  pathType: Prefix
          tls:
            - hosts:
                - rabbitmq.{{ .Values.global.domain }}
              secretName: {{ .Values.global.tlsSecret }}
  destination:
    server: https://kubernetes.default.svc
    namespace: rabbitmq
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
    - CreateNamespace=true
