apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: sins
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    repoURL: https://swipentap.github.io/charts
    chart: sins
    targetRevision: {{ .Values.sinsChartRevision | quote }}
    helm:
      releaseName: sins-release
      valuesObject:
        postgresql:
          enabled: false
        webui:
          enabled: true
          image:
            repository: judyandiealvarez/sins
            tag: "1.0.78"
          service:
            type: NodePort
            port: 80
            nodePort: 30084
          ingress:
            enabled: true
            className: traefik
            annotations:
              traefik.ingress.kubernetes.io.router.entrypoints: web,websecure
            tls:
              - hosts:
                  - ns.{{ .Values.global.domain }}
                secretName: {{ .Values.global.tlsSecret }}
          env:
            ConnectionStrings__DefaultConnection: "Host=postgresql-rw.postgresql.svc.cluster.local:5432;Database=dns_server;Username=sins;Password=sins123;"
          waitForPostgresql:
            enabled: true
            host: postgresql-rw.postgresql.svc.cluster.local
            port: 5432
          dbInit:
            enabled: true
            dbHost: postgresql-rw.postgresql.svc.cluster.local
            dbPort: "5432"
            adminUser: postgres
            adminPassword: postgres123
            appDatabase: dns_server
          dnsRecordsInit:
            enabled: true
            dbHost: postgresql-rw.postgresql.svc.cluster.local
            dbPort: "5432"
            dbName: dns_server
            dbUser: sins
            dbPassword: sins123
            haproxyIp: {{ .Values.sins.haproxyIp | quote }}
        sins:
          image:
            repository: judyandiealvarez/sins
            tag: "1.0.78"
          env:
            ConnectionStrings__DefaultConnection: "Host=postgresql-rw.postgresql.svc.cluster.local:5432;Database=dns_server;Username=sins;Password=sins123;"
          waitForPostgresql:
            enabled: true
            host: postgresql-rw.postgresql.svc.cluster.local
            port: 5432
        domain: {{ .Values.global.domain | quote }}
        subdomain: ns
        haproxyIp: {{ .Values.sins.haproxyIp | quote }}
  destination:
    server: https://kubernetes.default.svc
    namespace: sins
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
    - CreateNamespace=true
  ignoreDifferences:
  - kind: Ingress
    jsonPointers:
      - /status
