apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: tls-secret
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    repoURL: {{ .Values.chartsRepo | quote }}
    chart: tls-secret
    targetRevision: {{ .Values.tlsSecretChartRevision | quote }}
    helm:
      values: |
        secretName: {{ .Values.global.tlsSecret | quote }}
        {{- $envTls := index .Values.envTls .Values.global.env }}
        {{- $certCrt := .Values.tlsCrt | default (index $envTls "tlsCrt") }}
        {{- $certKey := .Values.tlsKey | default (index $envTls "tlsKey") }}
        {{- if $certCrt }}
        tlsCrt: {{ $certCrt | b64enc | quote }}
        tlsKey: {{ $certKey | b64enc | quote }}
        {{- end }}
  destination:
    server: https://kubernetes.default.svc
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
    - CreateNamespace=true
    - ServerSideApply=true
