apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: tls-secret
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    repoURL: {{ .Values.envaappsRepo | quote }}
    targetRevision: {{ .Values.envaappsRevision | quote }}
    path: manifests/tls
    directory:
      recurse: true
  destination:
    server: https://kubernetes.default.svc
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
    - CreateNamespace=true
    - ServerSideApply=true
