apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: vault-secrets
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    repoURL: {{ .Values.chartsRepo | quote }}
    chart: vault-secrets
    targetRevision: {{ .Values.vaultSecretsChartRevision | quote }}
    helm:
      releaseName: vault-secrets
      valuesObject:
        global:
          env: {{ .Values.global.env | quote }}
        vault:
          url: {{ .Values.vault.url | quote }}
          kubeAuthPath: {{ .Values.vault.kubeAuthPath | quote }}
          role: {{ .Values.vault.role | quote }}
  destination:
    server: https://kubernetes.default.svc
    namespace: vault-secrets
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
    - CreateNamespace=true
