{{- if and .Values.tlsCrt .Values.tlsKey }}
{{- range $i, $ns := .Values.namespaces }}
{{- if $i }}
---
{{- end }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ $.Values.secretName | quote }}
  namespace: {{ $ns | quote }}
type: kubernetes.io/tls
data:
  tls.crt: {{ $.Values.tlsCrt | quote }}
  tls.key: {{ $.Values.tlsKey | quote }}
{{- end }}
{{- end }}
