apiVersion: v1
kind: PersistentVolume
metadata:
  name: freeipa-data
spec:
  capacity:
    storage: {{ .Values.persistence.size }}
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  storageClassName: ""
  hostPath:
    path: {{ .Values.persistence.glusterMountPath }}
