apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: freeipa-data
  namespace: {{ .Release.Namespace }}
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: ""
  volumeName: freeipa-data
  resources:
    requests:
      storage: {{ .Values.persistence.size }}
