apiVersion: traefik.io/v1alpha1
kind: ServersTransport
metadata:
  name: insecure-skip-verify
  namespace: {{ .Release.Namespace }}
  labels:
    app.kubernetes.io/name: freeipa
    app.kubernetes.io/instance: {{ .Release.Name }}
spec:
  insecureSkipVerify: true
