apiVersion: apps/v1
kind: Deployment
metadata:
  name: freeipa
  namespace: {{ .Release.Namespace }}
  labels:
    app.kubernetes.io/name: freeipa
    app.kubernetes.io/instance: {{ .Release.Name }}
spec:
  replicas: 1
  strategy:
    type: Recreate
  selector:
    matchLabels:
      app.kubernetes.io/name: freeipa
      app.kubernetes.io/instance: {{ .Release.Name }}
  template:
    metadata:
      labels:
        app.kubernetes.io/name: freeipa
        app.kubernetes.io/instance: {{ .Release.Name }}
    spec:
      {{- if .Values.nodeSelector }}
      nodeSelector: {{- toYaml .Values.nodeSelector | nindent 8 }}
      {{- end }}
      {{- if .Values.tolerations }}
      tolerations: {{- toYaml .Values.tolerations | nindent 8 }}
      {{- end }}
      {{- if .Values.affinity }}
      affinity: {{- toYaml .Values.affinity | nindent 8 }}
      {{- end }}
      containers:
        - name: freeipa
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          {{- if .Values.securityContext }}
          securityContext: {{- toYaml .Values.securityContext | nindent 12 }}
          {{- end }}
          args:
            - -U
            - --realm={{ .Values.realm }}
            - --domain={{ .Values.domain }}
            - --ds-password=$(IPA_DS_PASSWORD)
            - --admin-password=$(IPA_ADMIN_PASSWORD)
            - --no-host-dns
            - --no-ntp
            - --unattended
          env:
            - name: IPA_SERVER_HOSTNAME
              value: {{ .Values.hostname | quote }}
            - name: IPA_SERVER_IP
              value: ""
            - name: IPA_ADMIN_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: {{ .Values.credentialsSecret }}
                  key: admin-password
            - name: IPA_DS_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: {{ .Values.credentialsSecret }}
                  key: ds-password
          ports:
            - containerPort: 80
              protocol: TCP
            - containerPort: 443
              protocol: TCP
            - containerPort: 389
              protocol: TCP
            - containerPort: 636
              protocol: TCP
            - containerPort: 88
              protocol: TCP
            - containerPort: 88
              protocol: UDP
            - containerPort: 464
              protocol: TCP
            - containerPort: 464
              protocol: UDP
          {{- if .Values.resources }}
          resources: {{- toYaml .Values.resources | nindent 12 }}
          {{- end }}
          readinessProbe:
            exec:
              command:
                - /usr/bin/systemctl
                - status
                - ipa
            initialDelaySeconds: 90
            timeoutSeconds: 10
            periodSeconds: 15
            successThreshold: 1
            failureThreshold: 6
          volumeMounts:
            - name: freeipa-data
              mountPath: /data
            - name: run
              mountPath: /run
            - name: tmp
              mountPath: /tmp
            - name: journal
              mountPath: /var/log/journal
            - name: cgroups
              mountPath: /sys/fs/cgroup
      volumes:
        - name: freeipa-data
          persistentVolumeClaim:
            claimName: freeipa-data
        - name: run
          emptyDir: {}
        - name: tmp
          emptyDir: {}
        - name: journal
          emptyDir: {}
        - name: cgroups
          hostPath:
            path: /sys/fs/cgroup
