apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: freeipa
  namespace: {{ .Release.Namespace }}
  labels:
    app.kubernetes.io/name: freeipa
    app.kubernetes.io/instance: {{ .Release.Name }}
spec:
  selector:
    matchLabels:
      app.kubernetes.io/name: freeipa
      app.kubernetes.io/instance: {{ .Release.Name }}
  replicas: 1
  podManagementPolicy: OrderedReady
  serviceName: freeipa
  template:
    metadata:
      labels:
        app.kubernetes.io/name: freeipa
        app.kubernetes.io/instance: {{ .Release.Name }}
    spec:
      {{- if .Values.nodeSelector }}
      nodeSelector: {{- toYaml .Values.nodeSelector | nindent 8 }}
      {{- end }}
      {{- if .Values.tolerations }}
      tolerations: {{- toYaml .Values.tolerations | nindent 8 }}
      {{- end }}
      {{- if .Values.affinity }}
      affinity: {{- toYaml .Values.affinity | nindent 8 }}
      {{- end }}
      {{- if .Values.podSecurityContext.enabled }}
      securityContext: {{- omit .Values.podSecurityContext "enabled" | toYaml | nindent 8 }}
      {{- end }}
      containers:
        - name: freeipa
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy | quote }}
          {{- if .Values.containerSecurityContext.enabled }}
          securityContext: {{- omit .Values.containerSecurityContext "enabled" | toYaml | nindent 12 }}
          {{- end }}
          {{- if .Values.diagnosticMode.enabled }}
          command: {{- toYaml .Values.diagnosticMode.command | nindent 12 }}
          args: {{- toYaml .Values.diagnosticMode.args | nindent 12 }}
          {{- else }}
          args:
            - -U
            - --realm={{ .Values.realm }}
            - --domain={{ .Values.domain }}
            - --ds-password=$(IPA_DS_PASSWORD)
            - --admin-password=$(IPA_ADMIN_PASSWORD)
            - --unattended
            {{- if .Values.args.nohostdns }}
            - --no-host-dns
            {{- end }}
            {{- if .Values.args.nontp }}
            - --no-ntp
            {{- end }}
            {{- if .Values.args.setupdns }}
            - --setup-dns
            {{- end }}
            {{- if and .Values.args.setupdns .Values.args.autoforwarders }}
            - --auto-forwarders
            {{- end }}
            {{- if and .Values.args.setupdns .Values.args.allowzoneoverlap }}
            - --allow-zone-overlap
            {{- end }}
            {{- if .Values.args.sshtrustdns }}
            - --ssh-trust-dns
            {{- end }}
          {{- end }}
          env:
            - name: IPA_SERVER_HOSTNAME
              value: {{ .Values.hostname | quote }}
            - name: IPA_SERVER_IP
              value: ""
            - name: IPA_ADMIN_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: {{ .Values.credentialsSecret }}
                  key: admin-password
            - name: IPA_DS_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: {{ .Values.credentialsSecret }}
                  key: ds-password
            {{- if .Values.extraEnv }}
            {{- range $key, $value := .Values.extraEnv }}
            - name: {{ $key }}
              value: {{ $value | quote }}
            {{- end }}
            {{- end }}
          ports:
            {{- if .Values.args.setupdns }}
            - containerPort: 53
              protocol: TCP
            - containerPort: 53
              protocol: UDP
            {{- end }}
            - containerPort: 80
              protocol: TCP
            - containerPort: 88
              protocol: TCP
            - containerPort: 88
              protocol: UDP
            - containerPort: 123
              protocol: UDP
            - containerPort: 389
              protocol: TCP
            - containerPort: 443
              protocol: TCP
            - containerPort: 464
              protocol: TCP
            - containerPort: 464
              protocol: UDP
            - containerPort: 636
              protocol: TCP
          {{- if .Values.resources }}
          resources: {{- toYaml .Values.resources | nindent 12 }}
          {{- end }}
          {{- if not .Values.diagnosticMode.enabled }}
          readinessProbe:
            exec:
              command:
                - /usr/bin/systemctl
                - status
                - ipa
            initialDelaySeconds: 60
            timeoutSeconds: 10
            periodSeconds: 10
            successThreshold: 1
            failureThreshold: 3
          {{- end }}
          volumeMounts:
            - name: freeipa-data
              mountPath: /data
            - name: freeipa-run
              mountPath: /run
            - name: freeipa-tmp
              mountPath: /tmp
            - name: freeipa-journal
              mountPath: /var/log/journal
            - name: cgroups
              mountPath: /sys/fs/cgroup
              readOnly: true
      volumes:
        - name: freeipa-run
          emptyDir: {}
        - name: freeipa-tmp
          emptyDir: {}
        - name: freeipa-journal
          emptyDir: {}
        - name: cgroups
          hostPath:
            path: /sys/fs/cgroup
  {{- if not .Values.persistence.enabled }}
        - name: freeipa-data
          emptyDir: {}
  {{- else }}
  volumeClaimTemplates:
    - metadata:
        name: freeipa-data
        {{- if .Values.persistence.annotations }}
        annotations: {{- toYaml .Values.persistence.annotations | nindent 10 }}
        {{- end }}
      spec:
        accessModes:
          {{- range .Values.persistence.accessModes }}
          - {{ . | quote }}
          {{- end }}
        resources:
          requests:
            storage: {{ .Values.persistence.size | quote }}
        {{- if .Values.persistence.storageClass }}
        {{- if eq .Values.persistence.storageClass "-" }}
        storageClassName: ""
        {{- else }}
        storageClassName: {{ .Values.persistence.storageClass | quote }}
        {{- end }}
        {{- end }}
  {{- end }}
