{{- if and .Values.externalDatabase.enabled .Values.externalDatabase.password (not .Values.externalDatabase.existingSecret) }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "keycloak.fullname" . }}-external-db
  labels:
    {{- include "keycloak.labels" . | nindent 4 }}
type: Opaque
stringData:
  password: {{ .Values.externalDatabase.password | quote }}
{{- end }}
