apiVersion: v2
name: enva-umbrella
description: Umbrella chart for enva ArgoCD Applications (cert-manager, certa, mailu, ollama, postgresql, rancher, sins, tls-secret) plus inlined github-runner and traefik (sub)
type: application
version: 1.0.0
appVersion: "1.0.0"
keywords:
  - argocd
  - applications
  - enva
