apiVersion: v1
kind: Secret
metadata:
  name: keycloak-initial-admin
  namespace: keycloak
  annotations:
    argocd.argoproj.io/sync-wave: "0"
stringData:
  username: admin
  password: {{ .Values.adminPassword | quote }}
