apiVersion: batch/v1
kind: Job
metadata:
  name: keycloak-db-init
  namespace: keycloak
  annotations:
    argocd.argoproj.io/sync-wave: "0"
    argocd.argoproj.io/hook: Sync
    argocd.argoproj.io/hook-delete-policy: BeforeHookCreation
spec:
  backoffLimit: 6
  template:
    spec:
      restartPolicy: OnFailure
      containers:
        - name: db-init
          image: postgres:15-alpine
          env:
            - name: DB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: keycloak-db-secret
                  key: password
          command:
            - /bin/sh
            - -c
            - |
              set -e
              echo "Waiting for PostgreSQL..."
              until PGPASSWORD="postgres123" psql -h postgresql-rw.postgresql.svc.cluster.local -p 5432 -U postgres -d postgres -c '\q'; do
                echo "Not ready, retrying..."
                sleep 2
              done
              echo "Creating role keycloak if not exists..."
              if ! PGPASSWORD="postgres123" psql -h postgresql-rw.postgresql.svc.cluster.local -p 5432 -U postgres -d postgres -tAc "SELECT 1 FROM pg_roles WHERE rolname='keycloak'" | grep -q 1; then
                PGPASSWORD="postgres123" psql -h postgresql-rw.postgresql.svc.cluster.local -p 5432 -U postgres -d postgres -c "CREATE ROLE keycloak WITH LOGIN PASSWORD '$DB_PASSWORD';"
                echo "Role keycloak created."
              else
                echo "Role keycloak already exists."
              fi
              echo "Creating database keycloak if not exists..."
              if ! PGPASSWORD="postgres123" psql -h postgresql-rw.postgresql.svc.cluster.local -p 5432 -U postgres -d postgres -tAc "SELECT 1 FROM pg_database WHERE datname='keycloak'" | grep -q 1; then
                PGPASSWORD="postgres123" psql -h postgresql-rw.postgresql.svc.cluster.local -p 5432 -U postgres -d postgres -c "CREATE DATABASE keycloak OWNER keycloak;"
                echo "Database keycloak created."
              else
                echo "Database keycloak already exists."
              fi
              PGPASSWORD="postgres123" psql -h postgresql-rw.postgresql.svc.cluster.local -p 5432 -U postgres -d postgres -c "GRANT ALL PRIVILEGES ON DATABASE keycloak TO keycloak;"
              echo "DB init done."
