apiVersion: v1
kind: Secret
metadata:
  name: keycloak-db-secret
  namespace: keycloak
  annotations:
    argocd.argoproj.io/sync-wave: "0"
stringData:
  username: keycloak
  password: {{ .Values.dbPassword | quote }}
