apiVersion: k8s.keycloak.org/v2alpha1
kind: KeycloakRealmImport
metadata:
  name: master-realm
  namespace: keycloak
  annotations:
    argocd.argoproj.io/sync-wave: "3"
spec:
  keycloakCRName: keycloak
  realm:
    id: master
    realm: master
    enabled: true
    components:
      org.keycloak.storage.UserStorageProvider:
        - name: freeipa
          providerId: ldap
          subComponents: {}
          config:
            vendor:
              - rhds
            connectionUrl:
              - ldap://freeipa.freeipa.svc.cluster.local:389
            bindDn:
              - uid=admin,cn=users,cn=accounts,{{ .Values.ldapBaseDn }}
            bindCredential:
              - placeholder
            usersDn:
              - cn=users,cn=accounts,{{ .Values.ldapBaseDn }}
            usernameLDAPAttribute:
              - uid
            rdnLDAPAttribute:
              - uid
            uuidLDAPAttribute:
              - ipaUniqueID
            userObjectClasses:
              - inetOrgPerson,organizationalPerson
            editMode:
              - READ_ONLY
            syncRegistrations:
              - "false"
            importEnabled:
              - "true"
            enabled:
              - "true"
    clients:
      - clientId: sonarqube
        protocol: saml
        enabled: true
        rootUrl: {{ .Values.sonarqubeUrl | quote }}
        adminUrl: {{ .Values.sonarqubeUrl | quote }}
        baseUrl: {{ .Values.sonarqubeUrl | quote }}
        redirectUris:
          - {{ printf "%s/*" .Values.sonarqubeUrl | quote }}
        attributes:
          saml.authnstatement: "true"
          saml.client.signature: "false"
          saml.force.post.binding: "true"
          saml.server.signature: "true"
          saml_name_id_format: username
          saml.encrypt: "false"
          saml.assertion.signature: "true"
        protocolMappers:
          - name: login
            protocol: saml
            protocolMapper: saml-user-property-mapper
            consentRequired: false
            config:
              attribute.name: login
              attribute.nameformat: Basic
              user.attribute: username
              friendly.name: login
              jsonType.label: ""
          - name: email
            protocol: saml
            protocolMapper: saml-user-property-mapper
            consentRequired: false
            config:
              attribute.name: email
              attribute.nameformat: Basic
              user.attribute: email
              friendly.name: email
              jsonType.label: ""
          - name: name
            protocol: saml
            protocolMapper: saml-user-property-mapper
            consentRequired: false
            config:
              attribute.name: name
              attribute.nameformat: Basic
              user.attribute: firstName
              friendly.name: name
              jsonType.label: ""
