apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: harbor-core-wait-credentials
  namespace: harbor
rules:
  - apiGroups: [""]
    resources: ["secrets"]
    resourceNames: ["harbor-credentials"]
    verbs: ["get"]
